[project]
name = "t20-score-predictor"
version = "0.1.0"
description = "Machine learning project for predicting T20 cricket scores using historical match data, feature engineering, and regression models"
readme = "README.md"

requires-python = ">=3.14"
dependencies = []

[project.scripts]
t20-score-predictor = "t20_score_predictor:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
